update to dev api doc
HewlettPackard/Galadriel pull request #12
Opened 2022-07-26 20:52 UTC by thisab

**Pull Request check list**

- [ ] Proper tests/regressions included?
- [x] Documentation updated?

**Affected functionality**

**Description of change**
Added podman option in Makefile for api-doc

**Which issue this PR fixes**

2022-07-27 12:22 UTC, n-th requested changes
I think it is better to not push testing code to the master branch. I would remove that and add just the updates you have done to the dev API doc.

2022-07-27 12:22 UTC, n-th commented on pkg/server/server.go
> +
The content below the function Run should be separated from this file, as they are only handlers for the API server. You can remove them from here and add them to the handler.go file inside the proper API.

2022-07-27 12:22 UTC, n-th commented on dev/api/harvester.html
> +        <elements-api apiDescriptionUrl="oapi-codegen/harvester.yaml" router="hash" />
I would change this path to allow devs to run the server for the documentation locally instead of only relying on running this on Docker/Podman. For that, the URLs and file paths would need to be the same inside the container and out of it.

2022-07-27 14:10 UTC, mchurichi commented
hey @thisab, glad you got the gorm stuff working!, but I agree with Nath that we shouldn't be pushing testing stuff to the master branch, better to have this in a personal branch or a gist if we want this to be shared with the team, and at the same time, we'd rather have atomic PRs addressing a single thing at the time to facilitate reviews.

2022-07-27 16:02 UTC, jufantozzi commented
Just to line out something here: before this PR was opened, I asked @thisab offline to keep the code he used for testing temporarily in the PR so it would facilitate testing for us, as reviewers 😃.  So the intent of the testing code is in fact to be removed (as stated in coments in the code) once we were done testing.

With that said, i'll be reviewing this and running my tests ASAP👍

2022-07-27 17:49 UTC, mgbcaio commented
Good work, @thisab. I agree with Maxi and Nathalia regarding the atomic PRs and the test chunk of code. I think if we really need to share this code we could have it in a [gist](https://gist.github.com/). We would only add in the main branch to remove it later anyways. 👍

2022-07-27 20:32 UTC, thisab commented on pkg/server/server.go
> +
Ok, moved this code to handle.go

2022-07-27 20:33 UTC, thisab commented on dev/api/harvester.html
> +        <elements-api apiDescriptionUrl="oapi-codegen/harvester.yaml" router="hash" />
Sure, but think doing "python3 -m http.server " on the same directory does not allow for accessing files on upper directories. I suggest looking into it later on.

2022-07-28 11:57 UTC, jufantozzi reviewed
Amazing work @thisab! 🏅 

Just left some minor comments and we should be good to go.

2022-07-28 11:57 UTC, jufantozzi commented on cmd/server/main.go
> -	var port = flag.Int("port", 8080, "Port for HTTP Galadriel server")
Accidentally removed?

2022-07-28 11:57 UTC, jufantozzi commented on pkg/server/datastore/models.go
> +//TODO - Remember that the DeletedAt is removed in Spire
Not that we should be worrying about this at this moment, but SPIRE doesn't seem to use `gorm.Model` for models that it doesn't want to be capable of doing deletions.

2022-07-28 11:57 UTC, jufantozzi commented on pkg/server/server.go
> -func (s Server) Run() {
accidental deletion?

2022-07-28 11:57 UTC, jufantozzi commented on pkg/server/server.go
>  // The code under api/petstore/ has been generated from that specification.
Could you please remove all these initial comments?

2022-07-28 12:23 UTC, thisab commented on pkg/server/server.go
>  // The code under api/petstore/ has been generated from that specification.
sure, removed on the last push

2022-07-28 12:23 UTC, thisab commented on pkg/server/server.go
> -func (s Server) Run() {
good call, readded the Run()

2022-07-28 12:28 UTC, thisab commented on cmd/server/main.go
> -	var port = flag.Int("port", 8080, "Port for HTTP Galadriel server")
Sure, readded

2022-07-28 12:32 UTC, jufantozzi approved these changes
💯

2022-07-28 13:10 UTC, thisab commented on pkg/server/datastore/models.go
> +//TODO - Remember that the DeletedAt is removed in Spire
Sure I agree.
Also, Ive spoken to Nathalia and we agreed on separating the DB code on another branch

2022-07-28 13:12 UTC, n-th approved these changes
🥓

2022-07-28 13:19 UTC, n-th submitted a review, later dismissed

2022-07-28 13:19 UTC, mchurichi submitted a review, later dismissed
🙌

2022-07-28 13:46 UTC, n-th approved these changes
👍

2022-07-28 14:00 UTC, mchurichi approved these changes

2022-07-28 14:32 UTC, merged