DB update
HewlettPackard/galadriel pull request #20
Opened 2022-08-01 18:22 UTC by thisab

**Pull Request check list**

- [ ] Proper tests/regressions included?
- [ ] Documentation updated?

**Affected functionality**
Added support for MySQL and PostgreSQL

**Description of change**

**Which issue this PR fixes**

2022-08-01 18:51 UTC, mchurichi commented
hey Thiago, any reason why you want to merge this into the `db` branch and not `master`? will you be using it as a feature branch?

2022-08-01 19:08 UTC, thisab commented
Hello Maximiliano, wont be a feature branch, was just a convention. What do you think @n-th ? Merge this into master?

2022-08-01 21:24 UTC, n-th commented
>  Hello Maximiliano, wont be a feature branch, was just a convention. What do you think @n-th ? Merge this into master? 
> > hey Thiago, any reason why you want to merge this into the db branch and not master? will you be using it as a feature branch?

The last PR related to db wasn't completed enough to be merged to the master branch, so we created this one to be an intermediate branch for the feature related to db in order to not pollute the main branch.

2022-08-02 15:32 UTC, mchurichi commented
> 

ok it makes sense, thanks to both

2022-08-02 17:18 UTC, mchurichi reviewed
Overall looks good to me 👌 
I know this is WIP and won't be merged into master now, but I left some minor comments to help start defining style and conventions over code in general.

2022-08-02 17:18 UTC, mchurichi commented on pkg/server/datastore/sqlstore/sqlstore.go
> +	}
super nit: this can be simplified like this
```suggestion
	if err := db.Where(&org).FirstOrCreate(&org).Error; err != nil {
		return fmt.Errorf("sqlstorage error: %v", err)
	}
	return nil
```

2022-08-02 19:35 UTC, thisab commented on pkg/server/datastore/sqlstore/sqlstore.go
> +
Yes, I think the intent is really start outlining the datastore interface. Any more suggestions on that interface?

2022-08-02 19:57 UTC, mchurichi commented on pkg/server/datastore/sqlstore/sqlstore.go
> +
Cool. So, I think it shouldn't be tied to a specific implementation (this gorm-based plugin, for instance). Maybe a DataStore interface that defines the contract for data store plugins, with the basic CRUD operations using agnostic data models, and your sqlstore plugin should implement this interface.
Something similar to what we have already started defining on the harvester side: https://github.com/HewlettPackard/galadriel/blob/c23c4a6317ebf8ed0672ea23aadd188f3f1b0d4e/pkg/harvester/spire/spire.go

2022-08-03 14:44 UTC, mgbcaio requested changes
Hey @thisab, left some comments! Let me know what you think. :)

2022-08-03 14:44 UTC, mgbcaio commented on pkg/server/datastore/sqlstore/postgres.go
> +type postgresDB struct{}
nit: 
```suggestion
type PostgresDB struct{}
```

2022-08-03 14:44 UTC, mgbcaio commented on pkg/server/datastore/sqlstore/sqlite.go
> +type sqliteDB struct{}
nit: 
```suggestion
type SqliteDB struct{}
```

2022-08-03 14:44 UTC, mgbcaio commented on pkg/server/datastore/sqlstore/sqlstore.go
> +		return result
```suggestion
	err := db.AutoMigrate(&Member{})
	if err != nil {
		fmt.Println("storage err: ", err)
		return err
```

2022-08-03 14:44 UTC, mgbcaio commented on pkg/server/datastore/sqlstore/sqlstore.go
> +	// Insert new ORG into the DB
```suggestion
// RetrieveOrg retrieves an Organization from the Database. returns an error if something goes wrong.
func RetrieveOrg(db *gorm.DB, org *Organization) error {
```
Having this comment for the other functions will help as well. I advise you to put comments in the other functions. It provides a better description of the function even if it is called outside the file.

2022-08-03 14:44 UTC, mgbcaio commented on pkg/server/datastore/sqlstore/sqlstore.go
> +	return nil
shouldn't we be returning the result, aka Organization?

2022-08-03 14:44 UTC, mgbcaio commented on pkg/server/datastore/sqlstore/sqlstore.go
> +	err := db.Where(br).First(br).Error
```suggestion
	result := db.Where(br).First(br)
```
and then use the `result.Error` for the error handling parts of the code.

2022-08-03 14:44 UTC, mgbcaio commented on pkg/server/datastore/sqlstore/sqlstore.go
> +	return nil
shouldn't we be returning the result from the DB transaction, aka `Bridge`?

2022-08-03 14:44 UTC, mgbcaio commented on pkg/server/datastore/sqlstore/models.go
> +	Model
Why use only `Model` instead of `gorm.Model` like the `Member`struct?

2022-08-04 10:16 UTC, thisab commented on pkg/server/datastore/sqlstore/sqlstore.go
> +	return nil
It does, but it searches for the parameter inside the Organization passed as argument. This function was changed in a new code that is local in my machine to search for a string and return the Organization.

2022-08-04 10:17 UTC, thisab commented on pkg/server/datastore/sqlstore/models.go
> +	Model
This is similar to the code in Spire. It removes the possibility of soft-deletion.

2022-08-04 10:17 UTC, thisab commented on pkg/server/datastore/sqlstore/sqlstore.go
> +	// Insert new ORG into the DB
ok

2022-08-04 10:20 UTC, thisab commented on pkg/server/datastore/sqlstore/mysql.go
> +type mysqlDB struct{}
Why would this struct be public?
the code before is similar in structure to Spire: https://github.com/spiffe/spire/blob/main/pkg/server/datastore/sqlstore/mysql.go

2022-08-04 10:21 UTC, thisab commented on pkg/server/datastore/sqlstore/dialect.go
> +type dialect interface {
Why would it be public?
The code was also similar to Spire code: https://github.com/spiffe/spire/blob/main/pkg/server/datastore/sqlstore/dialect.go

2022-08-04 10:22 UTC, thisab commented on pkg/server/datastore/sqlstore/sqlite.go
> +	}
ok

2022-08-04 10:22 UTC, thisab commented on pkg/server/datastore/sqlstore/postgres.go
> +	}
ok

2022-08-04 10:22 UTC, thisab commented on pkg/server/datastore/sqlstore/mysql.go
> +	}
ok

2022-08-04 10:24 UTC, thisab commented on pkg/server/datastore/sqlstore/postgres.go
> +type postgresDB struct{}
I think this should be private as per other suggestions

2022-08-04 14:33 UTC, mgbcaio commented on pkg/server/datastore/sqlstore/dialect.go
> +type dialect interface {
my bad, I thought you were using different packages. This leaves me wondering, will we be using this in another package?

2022-08-04 14:35 UTC, mgbcaio commented on pkg/server/datastore/sqlstore/sqlstore.go
> +	return nil
Oh, would you care to commit that to this PR so that it would be more consistent? thanks! 😊

2022-08-04 14:36 UTC, mgbcaio commented on pkg/server/datastore/sqlstore/models.go
> +	Model
Got it, so the `Member` struct would also need to be `Model` instead of `gorm.Model` ?

2022-08-04 18:36 UTC, thisab commented on pkg/server/datastore/sqlstore/dialect.go
> +type dialect interface {
Not outside the package, but by the function that opens DB using Gorm in a generic way (multiplexes into MySQL, Postgres or sqlite).

2022-08-04 18:36 UTC, thisab commented on pkg/server/datastore/sqlstore/models.go
> +	Model
sure would, changed it

2022-08-04 18:37 UTC, thisab commented on pkg/server/datastore/sqlstore/sqlite.go
> +type sqliteDB struct{}
I think this should be private as per other suggestions.

2022-08-04 18:44 UTC, thisab commented on pkg/server/datastore/sqlstore/sqlstore.go
> +	return nil
hum.. thinking about the creation workflow: the code that asks for the creation of, say Bridge, would have already created a Bridge "object" and passed it as an argument to this function. So the code that called the function would already have the it and might only be interested in knowing whether the operation succeeded.

2022-08-10 17:10 UTC, thisab commented on pkg/server/datastore/sqlstore/sqlstore.go
> +		return nil, errors.New("unsupported database_type: %s" + dbtype)
sure, ok

2022-08-11 17:03 UTC, thisab reviewed
Reviewed the suggestions and compiled them in the most recent commit

2022-08-11 17:08 UTC, thisab reviewed
For this code I intend to add the implementation of the abstration layer (interface) later on. That way seems to make more sense as we define the API first. What do you think?

2022-08-14 02:34 UTC, jufantozzi reviewed
Hey Thiago! thanks for this! Overall looking really good!

One thing that cought my attention is that we're starting off supporting muiltiple databases, and I could be wrong here, but my concern is that this could make it difficult to maintain further on, just adding extra overhead. 

Again, my lack of knowledge on gorm could mislead me here but IIRC we agreed on sqlite for the POC, and I'd probably vote for us to keep on that track, but would love you hear you back on this.

2022-08-14 02:34 UTC, jufantozzi commented on pkg/server/datastore/sqlstore/models.go
> +	SourceMemberConsent bool
One thing that I was thinking about this is that "Source/Target" concepts makes sense if relationships are member initiates, but what if they were server initiated? Would Source/Target still make sense?

2022-08-15 11:26 UTC, thisab commented
> Hey Thiago! thanks for this! Overall looking really good!
> 
> One thing that cought my attention is that we're starting off supporting muiltiple databases, and I could be wrong here, but my concern is that this could make it difficult to maintain further on, just adding extra overhead.
> 
> Again, my lack of knowledge on gorm could mislead me here but IIRC we agreed on sqlite for the POC, and I'd probably vote for us to keep on that track, but would love you hear you back on this.

Regarding multiple DBs, there were no added complexity by using MySQL and Postgre. Just two files were needed and thats it. Basic functions are the same.

2022-08-15 11:31 UTC, jufantozzi commented
> Regarding multiple DBs, there were no added complexity by using MySQL and Postgre. Just two files were needed and thats it. Basic functions are the same.

Right, true for basic functions, but will this remain true when we start implementing the wanted behavior? My concern is that futurely we'd find out that there are many differences and this would pose unwanted difficulties...

2022-08-15 11:33 UTC, thisab commented on pkg/server/datastore/sqlstore/models.go
> +	SourceMemberConsent bool
If its server initiated, the status could change to reflect the server initiated approval. Source/Target does not have a meaning in that context, but its already there for that feature to be implemented later on.

2022-08-15 11:51 UTC, thisab commented
> > Regarding multiple DBs, there were no added complexity by using MySQL and Postgre. Just two files were needed and thats it. Basic functions are the same.
> 
> Right, true for basic functions, but will this remain true when we start implementing the wanted behavior? My concern is that futurely we'd find out that there are many differences and this would pose unwanted difficulties...

For the present, actually SQLite was a little harder because of manual cascading code. 
Cant say for the future. Gorm can even handle advanced queries well. Unless we start seeing bugs with gorm or start needing to handle raw queries.

For us to move on, then we can just delete the files mysql.go and postgres.go and thats it. No support for those two DBs. Agreed?

2022-08-15 11:52 UTC, jufantozzi commented
> For us to move on, then we can just delete the files mysql.go and postgres.go and thats it. No support for those two DBs. Agreed?

Since what he have here works, my suggestion is that we keep it, and see if in the future is still easy to support. If we find otherwise, then we can drop it. WDYT?

2022-08-15 11:59 UTC, thisab commented
> > For us to move on, then we can just delete the files mysql.go and postgres.go and thats it. No support for those two DBs. Agreed?
> 
> Since what he have here works, my suggestion is that we keep it, and see if in the future is still easy to support. If we find otherwise, then we can drop it. WDYT?

Agreed, as it is easy to remove support later on.

2022-08-15 12:07 UTC, jufantozzi approved these changes
🌳

2022-08-15 13:40 UTC, jufantozzi approved these changes

2022-08-15 13:41 UTC, mchurichi submitted a review, later dismissed

2022-08-15 13:41 UTC, mchurichi commented on pkg/server/datastore/sqlstore/sqlstore.go
> +func CreateAllTablesinDB(db *gorm.DB) (err error) {
since you are explicitly returning err, we can remove the named return values as it is redundant and confusing
```suggestion
func CreateAllTablesinDB(db *gorm.DB) error {
```

2022-08-15 13:41 UTC, mchurichi commented on pkg/server/datastore/sqlstore/sqlstore.go
> +	}
nit: we could simplify all err handlings in this file
```suggestion
	if err := CreateOrganizationTableInDB(db); err != nil;  {
		return err
	}
```

2022-08-15 13:41 UTC, mchurichi commented on pkg/server/datastore/sqlstore/sqlstore.go
> +func CreateOrganization(db *gorm.DB, org Organization) error {
is there a reason to not return the newly created organization? (the same applies to all create and update functions)
not having the org id, for instance, may be problematic when creating entities and their subentities like bridges and members

2022-08-15 13:41 UTC, mchurichi commented on pkg/server/datastore/sqlstore/sqlstore.go
> +func CreateMember(db *gorm.DB, mem Member, description string) error {
description is not being used

2022-08-15 13:41 UTC, mchurichi commented on pkg/server/datastore/sqlstore/sqlstore.go
> +package sqlstore
as a general comment on this package, I don't think we should be relying on weak properties like names and descriptions to fetch entities, e.g. a function to create a membership should be passed in immutable properties like both member ids and the bridge id, not names or descriptions, that are likely to be changed.

2022-08-15 13:41 UTC, mchurichi commented on pkg/server/datastore/sqlstore/sqlstore.go
> +func RetrieveAllMembersbyBridgeID(db *gorm.DB, bridgeID uint) (mem *[]Member, err error) {
I think in general we shouldn't be creating a function per property we have in each entity, as this is hard to maintain. I'd propose 2 functions per entity, a simple one to fetch by id, and another that receives an object with the properties we want to fetch, something like
```go
func RetrieveMemberById(id int) (Member, error) ...
func RetrieveMembers(properties Member) ([]*Member, error) ...
```
what do you think?

2022-08-15 13:41 UTC, mchurichi commented on pkg/server/datastore/sqlstore/sqlstore.go
> +	// RetrieveMembershipbyToken retrieves a Membership from the Database bigger than an specific date. returns an error if something goes wrong.
function comments must of above the function name

2022-08-15 13:44 UTC, mchurichi commented on pkg/server/datastore/sqlstore/sqlstore.go
> +func CreateOrganizationTableInDB(db *gorm.DB) error {
we agree these functions need to be part of the struct, right? probably not for this PR, but we need these grouped and behind a well-defined interface

2022-08-15 14:10 UTC, thisab commented on pkg/server/datastore/sqlstore/sqlstore.go
> +		return fmt.Errorf("Organization " + org.Name + " does not exist in DB")
I think this is outdated. Not present in the most recent code.

2022-08-15 14:11 UTC, thisab commented on pkg/server/datastore/sqlstore/sqlstore.go
> +		return fmt.Errorf("Bridge Description=" + br.Description + " does not exist in DB")
I think this is outdated. Not present in the most recent code.

2022-08-15 14:11 UTC, thisab commented on pkg/server/datastore/sqlstore/sqlstore.go
> +		return fmt.Errorf("Member SpiffeID=" + mem.SpiffeID + " does not exist in DB")
I think this is outdated. Not present in the most recent code.

2022-08-15 14:13 UTC, thisab commented on pkg/server/datastore/sqlstore/sqlstore.go
> +func CreateOrganization(db *gorm.DB, org Organization) error {
Could be rewritten to return always the entity created. Looking into the Spire code, it does that. So, I think we could do that here too.

2022-08-15 14:14 UTC, thisab commented on pkg/server/datastore/sqlstore/sqlstore.go
> +package sqlstore
Agreed that, although unique, they could change with time.

2022-08-15 17:20 UTC, thisab reviewed
Made changes according to mchurichi inputs.

2022-08-15 17:20 UTC, thisab commented on pkg/server/datastore/sqlstore/sqlstore.go
> +func RetrieveAllMembersbyBridgeID(db *gorm.DB, bridgeID uint) (mem *[]Member, err error) {
Agreed. I rewrote to focus more on ID values.

2022-08-15 17:20 UTC, thisab commented on pkg/server/datastore/sqlstore/sqlstore.go
> +func CreateOrganizationTableInDB(db *gorm.DB) error {
Yes. Later on this could be part of a Plugin struct, just like Spire is.

2022-08-15 18:00 UTC, jufantozzi commented
One observation for the future: let's try to avoid large PRs as it's usually easier to deal with smaller ones 😃

2022-08-16 12:39 UTC, thisab reviewed
Applied the requested changes to the code

2022-08-16 12:40 UTC, thisab commented
> One observation for the future: let's try to avoid large PRs as it's usually easier to deal with smaller ones smiley

Sure, we will work on that

2022-08-16 14:27 UTC, maxlambrecht commented on pkg/server/datastore/sqlstore/models.go
> +type Member struct {
IMO we should only add the fields we know we'll need for a POC or maybe a MVP, and then incrementally add the extra fields when the necessity for them comes, otherwise it could happen that we end up with fields in the DB that we never need and nobody knows why they are there.

2022-08-16 20:41 UTC, thisab commented on pkg/server/datastore/sqlstore/models.go
> +type Member struct {
Sure, I will clean it up. Then upload them again.

2022-08-17 12:38 UTC, mchurichi commented
> As discussed offline, I'll be approving this as it is to avoid making this PR even bigger, but we agreed that there's some technical debt that should be taken care of right away:
> 
>     * Basic unit tests and
> 
>     * Defining interfaces for the db plugin for CRUD operations.
> 
> 
> These interfaces will be used by the database broker (the layer above this current impl) and they are needed to properly separate the domains.

Agreed. This is not even getting merged on the main branch, and refactors and improvements can be made in smaller PRs to ease the review process.

2022-08-17 12:38 UTC, mchurichi approved these changes

2022-08-17 12:52 UTC, merged