Adds `server run` command to server CLI
HewlettPackard/galadriel pull request #24
Opened 2022-08-02 21:01 UTC by miguelfferraz

Signed-off-by: Miguel Figueira Ferraz <miguelfigueiraferraz@gmail.com>

**Pull Request checklist**

- [ ] Proper tests/regressions included?

- [ ] Documentation updated?

**Affected functionality**
Adds a new command `server run` to CLI, this command starts the Galadriel Server.

**Description of change**
The code inside `/cmd/server/main.go` was moved to `/cmd/server/api/api.go`. Now main.go only starts the CLI, while api.go handles starting Galadriel Server.
A new package called `cli` has been created inside `/cmd/server`. This package contains all CLI commands.

2022-08-02 21:30 UTC, mchurichi reviewed
Nicely done, Miguel! 🙌 

It seems that there are a few files that are missing a gofmt pass, could you give it a run? Other than that, this looks great to me.

2022-08-02 21:30 UTC, mchurichi commented on cmd/server/cli/run.go
> +	Long: `Run this command to start HTTP Galadriel server`,
super nit
```suggestion
	Long:  "Run this command to start HTTP Galadriel server",
```

2022-08-02 21:30 UTC, mchurichi commented on cmd/server/cli/server.go
> +	Long: `Commands to manage Galadriel server`,
super nit
```suggestion
	Long:  "Commands to manage Galadriel server",
```

2022-08-02 21:33 UTC, mchurichi commented
And one more thing, could you add a super simple readme for the Server CLI? the idea is to document it from the very beginning, something like the [Harvester doc](https://github.com/HewlettPackard/galadriel/blob/master/doc/harvester.md)

2022-08-03 21:05 UTC, mchurichi commented
@mgbcaio any thoughts here?

2022-08-04 11:22 UTC, n-th commented
@miguelfferraz , can you add a help command as well as unit tests?

2022-08-04 11:54 UTC, mgbcaio commented
I agree with @mchurichi and @n-th. Other than that, I think we could follow the same development pattern @mchurichi implemented regarding the harvester CLI -> [Maxi PR](https://github.com/HewlettPackard/galadriel/pull/16/files). What do you guys think?

2022-08-04 14:01 UTC, mchurichi commented
Just to be clear, the CLI pushed in the [Boilerplate PR](https://github.com/HewlettPackard/galadriel/pull/16/files) was only intended to define the basic directories and interfaces architecture. The tooling choices (no external lib, in the case of the CLI) shouldn't be taken into account.

That said, I like the idea of using a specialized CLI library like cobra or viper for this, but I'll rely on @miguelfferraz and @mgbcaio's (who's working on the CLI of the harvester) proposals for that, you guys should agree on tooling and style to have the same stuff on both Server and Harvester side.

2022-08-04 14:20 UTC, mgbcaio commented
> Just to be clear, the CLI pushed in the [Boilerplate PR](https://github.com/HewlettPackard/galadriel/pull/16/files) was only intended to define the basic directories and interfaces architecture. The tooling choices (no external lib, in the case of the CLI) shouldn't be taken into account.
> 
> That said, I like the idea of using a specialized CLI library like cobra or viper for this, but I'll rely on @miguelfferraz and @mgbcaio's (who's working on the CLI of the harvester) proposals for that, you guys should agree on tooling and style to have the same stuff on both Server and Harvester side.

That makes sense, thanks for clearing that out, Maxi! Considering that the Harverter CLI will follow the Cobra library, just like @miguelfferraz its doing.

2022-08-04 14:32 UTC, mchurichi commented on cmd/server/cli/root.go
> +		os.Exit(1)
what do you think about moving this to cmd/server/main.go? the CLI should be environment-agnostic... we can have this function returning an integer, and the main fn is the one that spits the return code back to the shell. This will make facilitate CLI testing without having to mock the os.Exit call.

2022-08-05 19:23 UTC, miguelfferraz commented on cmd/server/cli/root.go
> +		os.Exit(1)
> what do you think about moving this to cmd/server/main.go? the CLI should be environment-agnostic... we can have this function returning an integer, and the main fn is the one that spits the return code back to the shell. This will facilitate CLI testing without having to mock the os.Exit call.

Thanks for this suggestion, that makes sense. I moved os.Exit call to cmd/server/main.go.

2022-08-05 19:28 UTC, miguelfferraz commented
> @miguelfferraz , can you add a help command as well as unit tests?

@n-th Cobra already generates a help command and a --help flag for all commands in the CLI.
I'm working on the unit tests.

2022-08-12 18:20 UTC, jufantozzi requested changes
Thank you @miguelfferraz! Nice work! this looks great. I just left some minor observations but once we're done with those we're good to go 👌

2022-08-12 18:20 UTC, jufantozzi commented on cmd/server/cli/root.go
> +import (
I think it's worth to already start splitting each one of these into their own packages to avoid big refactors afterwards

2022-08-12 18:20 UTC, jufantozzi commented on cmd/server/cli/run.go
> +		Short: "Start HTTP Galadriel server",
```suggestion
		Short: "Runs the Galadriel server",
```

2022-08-12 18:20 UTC, jufantozzi commented on cmd/server/cli/run.go
> +		Long:  "Run this command to start HTTP Galadriel server",
```suggestion
		Long:  "Run this command to start the Galadriel server",
```

2022-08-16 18:17 UTC, mchurichi commented on cmd/server/cli/run_test.go
> +		fmt.Printf("%s", err)
we should be using an assert here, and making sure that if the function call returns an error the test must fail

2022-08-17 20:57 UTC, jufantozzi commented
Hey miguel, I tried building and running but the command prompt doesn't seem to return anything for any command. I didn't have enough time to debug it yet, PTAL.

2022-08-18 18:07 UTC, maxlambrecht commented on cmd/server/api/api.go
> +	// Clear out the servers array in the swagger spec, that skips validating
Remove all the unnecessary comments and commented code.

2022-08-19 00:18 UTC, miguelfferraz commented
> Hey miguel, I tried building and running but the command prompt doesn't seem to return anything for any command. I didn't have enough time to debug it yet, PTAL.

Thanks for the warning Juliano, the CLI is really with a bug on execution.

2022-08-24 22:01 UTC, jufantozzi requested changes
Threw a few more nits, but the only real concern here is allowing the server to start without properly loading the config.

> The problem is because I split the commands into different packages, I didn't figure out how to get this work.

AFAIK the way to go here would be to manually add the commands to the rootCmd, but it does look less clean IMO... We shouldn't have a problem going with the way it is, at least for now.

2022-08-25 11:00 UTC, jufantozzi commented
Oh, and please @miguelfferraz  make sure to have resolve the conflicts and to have signed all commits so we don't get dismissed approves.

2022-08-26 22:22 UTC, jufantozzi commented
Hi Miguel, we're almost good to go! Just need to sign the commits now. 

If you're unsure about what I'm referring to, [here's a reference](https://superuser.com/a/1123928) (this assumes you have gpg signing set up, the `-S` flag)

2022-08-30 13:46 UTC, mchurichi commented on conf/server/server.conf
> +    spire_socket_path = "/tmp/spire-server/private/api.sock"
please remove this setting, we won't need to connect to the spire server from the galadriel server

2022-08-30 13:46 UTC, mchurichi commented on conf/server/server.conf
> +    server_address = "localhost:8080"
```suggestion
    # listen_address: DNS name or IP address with port for the Galadriel Server to listen on
    # E.g: localhost:8080, my-upstream-server.com:4556, 192.168.1.125:4000
    # Default: localhost:8080
    listen_address = "localhost:8080"
```

2022-08-30 13:46 UTC, mchurichi commented on pkg/server/config/config.go
> +	SpireSocketPath string `hcl:"spire_socket_path"`
remove

2022-08-30 13:46 UTC, mchurichi commented on pkg/server/config/config.go
> +	ServerAddress   string `hcl:"server_address"`
```suggestion
	ListenAddress   string `hcl:"listen_address"`
```

2022-08-30 13:46 UTC, mchurichi commented on pkg/server/config/config.go
> +	if c.ServerConfigSection.SpireSocketPath == "" {
remove

2022-08-30 13:46 UTC, mchurichi commented on pkg/server/config/config.go
> +	}
please add ListenAddress default value to `localhost:8080`

2022-08-30 13:46 UTC, mchurichi commented on pkg/server/config/disk.go
> +package config
not for this PR, but we need to move this to a common package to be shared with the Harvester and Server to avoid code duplication

2022-08-30 14:28 UTC, mchurichi commented
Hi @miguelfferraz, I'm very sorry for the delay in getting this merged in 🙏

Just left some comments about the config file. There are a few things we won't need on the Server side.
I think we'll be good to merge this once we get those changes addressed.

Happy to discuss this offline on Slack or in a call if needed. Feel free to reach out.

2022-08-30 14:45 UTC, jufantozzi commented on pkg/server/config/disk.go
> +package config
...and to properly separate domains and avoid coupling. This should be addressed in other PR's soon.

2022-08-30 20:14 UTC, mchurichi commented on cmd/server/cli/run.go
> +			runServerFn(configPath)
one last request: can we have the same return pattern as in the harvester? let's try to keep both harvester and server code as close as possible
https://github.com/HewlettPackard/galadriel/pull/37/files#diff-c89d406f570ba5152de10698eb3b4ed24702ae7d03eb6c95563e832bffe2d638R26

2022-08-30 22:58 UTC, mchurichi commented on cmd/server/cli/run.go
> +			runServerFn(configPath)
and I swear this is the last one 😆

2022-08-31 13:42 UTC, mchurichi approved these changes
Excellent work @miguelfferraz! 🏅 Thank you so much! 🙏

2022-08-31 13:44 UTC, jufantozzi approved these changes
Thank you so much for your hard work and patience @miguelfferraz!

2022-08-31 13:45 UTC, merged