Added Server definition for the API interface
HewlettPackard/galadriel pull request #30
Opened 2022-08-11 16:42 UTC by thisab

**Pull Request check list**

- [ ] Proper tests/regressions included?
- [ ] Documentation updated?

**Affected functionality**

**Description of change**
Defined the Server and made the Server implement (dummy) functions for the API

**Which issue this PR fixes**

2022-08-15 13:26 UTC, mchurichi commented on pkg/server/api/management/handler.go
> +type Server struct {
can we define the actual interface this struct implements?

2022-08-15 15:13 UTC, n-th requested changes
I found some typos in the function, could you revise the .yamls that generate those functions for misspells?

2022-08-15 15:13 UTC, n-th commented on pkg/server/api/management/handler.go
> +func (server Server) UpdateOrganizaion(ctx echo.Context, orgID int64) error {
UpdateOrganization

2022-08-15 15:13 UTC, n-th commented on pkg/server/api/management/handler.go
> +func (server Server) UpdateFederationRelationshipship(ctx echo.Context, relationshipID int64) error {
UpdateFederationRelationship

2022-08-15 15:13 UTC, n-th commented on pkg/server/api/management/handler.go
> +func (server Server) DeletefederationGroupMembership(ctx echo.Context, membershipID int64) error {
DeleteFederationGroupMembership

2022-08-15 15:13 UTC, n-th commented on pkg/server/api/management/handler.go
> +func (server Server) DeletefederationGroupMembership(ctx echo.Context, membershipID int64) error {
This seems to happen to all federationGroupMembership related functions

2022-08-15 16:30 UTC, thisab commented on pkg/server/api/management/handler.go
> +func (server Server) UpdateOrganizaion(ctx echo.Context, orgID int64) error {
Indeed. To do that, we would need to include management.yaml file and correct it also.

2022-08-17 16:11 UTC, maxlambrecht commented on pkg/server/api/management/handler.go
> +func (server Server) GetSpireServers(ctx echo.Context, params GetSpireServersParams) error {
What's the reason for not using the `context.Context` from the standard library?

2022-08-22 20:39 UTC, thisab commented on pkg/server/api/management/handler.go
> +func (server Server) GetSpireServers(ctx echo.Context, params GetSpireServersParams) error {
@maxlambrecht we are using context of the Echo library, following just like the main.go does nowadays.
Do you think we should not follow that ?

2022-08-23 19:29 UTC, jufantozzi commented on pkg/server/api/management/handler.go
> +func (server Server) GetSpireServers(ctx echo.Context, params GetSpireServersParams) error {
AFAIK this is how the lib works, this `ctx` will have the request details

2022-08-23 19:44 UTC, maxlambrecht commented on pkg/server/api/management/handler.go
> +func (server Server) GetSpireServers(ctx echo.Context, params GetSpireServersParams) error {
We should use the `context.Context` from the standard library in all our APIs definitions. Our APIs should be as standard as possible, if in our implementation we use some library that needs a specific context struct, we'll need to "adapt" the standard ctx to it, but that specific context is an implementation detail that must not be leaked into the public interface.

2022-08-25 18:22 UTC, wiliamsouza commented on pkg/server/api/management/handler.go
> +func (server Server) GetSpireServers(ctx echo.Context, params GetSpireServersParams) error {
I was doing a little research to discover a way to keep using the echo as our web framework but it seems like there is no way to use it without using it’s  own context (`echo.Context` implementation[1]). Searching around I have found out that what other people do is to adapt/convert from `echo.Context` to Go lang `context.Context` before calling downstream code. This way it decouples the inner layers from your web framework API code. The main benefits of this approach is to isolate/decouple web frameworks or ORM from Galadriel  main business logic. May I upload the suggested change to this PR showing that solution?

PS: Maybe use the Go lang `internal` package to enforce that isolation[3] can be an option.

[1] https://stackoverflow.com/questions/47843914/transforming-echo-context-to-context-context
[2] https://github.com/labstack/echo/issues/1175#issuecomment-455226401
[3] https://dave.cheney.net/2019/10/06/use-internal-packages-to-reduce-your-public-api-surface

2022-08-25 18:58 UTC, maxlambrecht commented on pkg/server/api/management/handler.go
> +func (server Server) GetSpireServers(ctx echo.Context, params GetSpireServersParams) error {
You are right, it seems that we need to use the `echo.Context`.

2022-09-06 12:00 UTC, thisab commented
@jufantozzi I think this PR is a bit outdated. Does it still make sense to leave it open?

2022-09-06 12:04 UTC, jufantozzi commented
@thisab you're right, we can close this

2022-09-06 12:04 UTC, closed without merging