Harvester/cli
HewlettPackard/galadriel pull request #37
Opened 2022-08-21 14:23 UTC by n-th

**Pull Request check list**

- [X] Proper tests/regressions included?
- [ ] Documentation updated?

**Affected functionality**

**Description of change**

**Which issue this PR fixes**

2022-08-22 13:00 UTC, mchurichi commented
Thanks for caring care of this @n-th 🙏 It looks really good 💯 
I left some nit questions mostly about error handling, subcommands, and the execution path.

2022-08-22 13:47 UTC, n-th commented on cmd/harvester/cli/management.go
> +	if action == telemetry.List {
Kay, this will be addressed in an upcoming pr

2022-08-22 17:10 UTC, maxlambrecht requested changes

2022-08-22 17:10 UTC, maxlambrecht commented on cmd/harvester/cli/root.go
> +		return 1
Here it could be printed the error to the std output before returning the code. Make sure that the error returned by `cmdExecute` has all the context and information to be user friendly.

2022-08-23 20:44 UTC, mchurichi approved these changes
LGTM 💯

2022-08-24 13:42 UTC, maxlambrecht commented on cmd/harvester/cli/api.go
> +		c.logger.Error("Error loading config:", err)
This _log and return_ is generating a duplicate error log entry. _Log and return_ is usually an anti-pattern, just return the error and let the caller handle it. 
(In fact the error is logged 3 times on the terminal, I don't know where the third one comes from.)

2022-08-24 13:42 UTC, maxlambrecht commented on cmd/harvester/cli/cli.go
> +		c.logger.Error("Error when executing the Harvester CLI", err)
```suggestion
		c.logger.Error("Error when executing the Harvester CLI:", err)
```

2022-08-24 15:30 UTC, mgbcaio approved these changes
Awesome work, Nathalia! 🦾

2022-08-24 16:28 UTC, n-th commented on cmd/harvester/cli/api.go
> +		c.logger.Error("Error loading config:", err)
Done. One error is from LoadFromDisk, the other is from the RunE function of the cli and the other one is from Execute

2022-08-24 17:31 UTC, mchurichi commented on pkg/harvester/config/config.go
> +		return nil, errors.New(fmt.Sprintf("unable to decode configuration: %v", err))
nit: fmt.Errorf is a shortcut for errors.Next + fmt.Sprintf
```suggestion
		return nil, fmt.Errorf("unable to decode configuration: %v", err)
```

2022-08-24 17:43 UTC, n-th commented on pkg/harvester/config/config.go
> +		return nil, errors.New(fmt.Sprintf("unable to decode configuration: %v", err))
🤦‍♀️

2022-08-25 13:59 UTC, jufantozzi commented on cmd/harvester/cli/cli.go
> +		Long: "This is Galadriel Harvester CLI",
```suggestion
		Long: "This is the Galadriel Harvester CLI",
```

2022-08-25 13:59 UTC, jufantozzi commented on cmd/harvester/cli/cli.go
> +var HarvesterCLI = &HarvesterCli{
nit: place all var declarations next to each other

2022-08-25 13:59 UTC, jufantozzi commented on cmd/harvester/cli/api.go
> +	runCmd.PersistentFlags().StringVar(&configPath, "config", defaultConfigPath, "config file")
```suggestion
	runCmd.PersistentFlags().StringVarP(&configPath, "config", "c", defaultConfigPath, "config file")
```

2022-08-25 14:04 UTC, n-th commented on cmd/harvester/cli/management.go
> +		Use:   "manage",
I think we should have `harvester run` for the server and include the config command, `harvester manage` for the management, and then the subcommand about the management objects, verbs, and ids.

2022-08-26 21:24 UTC, mchurichi commented on cmd/harvester/cli/management.go
> +		Use:   "manage",
Agree with @jufantozzi, let's try to shrink the subcommands depth

2022-08-29 09:50 UTC, jufantozzi commented on cmd/harvester/cli/api.go
> +	c.logger.Info("Configuring Harvester Cli")
I agree. My opinion is that the CLI "framework" startup was not something actually informative, whereas the actual server startup is.

2022-08-30 12:23 UTC, maxlambrecht submitted a review, later dismissed
🍪

2022-08-30 12:32 UTC, jufantozzi commented
We're still seeing duplicated error messages when executing the CLI. Could you please fix that @n-th ?

2022-08-30 14:20 UTC, mchurichi commented on cmd/harvester/cli/api.go
> +	c.logger.Info("Configuring Harvester Cli")
Oh right, I didn't realize this is the CLI stuff, not a server or any other component... I'd change this to something like
```suggestion
	c.logger.Debug("Starting Harvester")
```
Or even remove this logging completely. The CLI is just the mechanism we use to spin the Harvester API up, not sure if having this log is useful for an operator trying to debug an issue.

2022-08-30 14:20 UTC, mchurichi commented on cmd/harvester/cli/api.go
> +		c.logger.Error("Configuring Harvester Cli")
```suggestion
		c.logger.Error("Error loading Harvester config:", err)
		return
```
Not sure if this is going to interpolate the err message properly. Feel free to make the message using fmt.Sprintf if needed.
Note for future task: Add `Errorf`, `Infof`, etc to the logging interface

2022-08-30 14:20 UTC, mchurichi commented on cmd/harvester/cli/cli.go
> +	c.logger.Info("Starting the Harvester CLI")
I don't think we need this

2022-08-30 14:32 UTC, maxlambrecht commented on cmd/harvester/cli/cli.go
> +type HarvesterCli struct {
Rename to `HarvesterCLI`, CLI is an acronym, should have a consistent case: https://github.com/golang/go/wiki/CodeReviewComments#initialisms

2022-08-30 14:52 UTC, mchurichi requested changes

2022-08-30 14:52 UTC, mchurichi commented on cmd/harvester/cli/management.go
> +			HarvesterCLI.runManagementAPI()
let's remove this for now, we still don't have the clients to make the API calls to the management API server

2022-08-30 14:52 UTC, mchurichi commented on cmd/harvester/cli/management.go
> +	c.logger.Info("Starting Management API")
same

2022-08-30 15:02 UTC, mchurichi commented on cmd/harvester/cli/api.go
> +		hc.logger.Error("Error loading Harvester config:", err)
We need to stop the execution here as the config couldn't be loaded. How about having this function return an error and handling it when called above?

2022-08-30 15:05 UTC, mchurichi commented on cmd/harvester/cli/management.go
> +			HarvesterCmd.runManagementAPI()
Oops, I think my previous comment got deleted. I suggested removing this fn call, and just have a placeholder for now as we still don't have the clients to call the Management API.

2022-08-30 15:07 UTC, mchurichi commented on cmd/harvester/cli/api.go
> +			configPath, _ := cmd.Flags().GetString("config")
please add error handling here

2022-08-30 20:05 UTC, mchurichi approved these changes
thank you @n-th! really appreciate all your hard work on getting this through the review!
💯

2022-08-30 20:19 UTC, jufantozzi approved these changes
Thank you @n-th!

2022-08-30 20:19 UTC, merged