Refactoring codebase
HewlettPackard/galadriel pull request #47
Opened 2022-09-09 14:25 UTC by maxlambrecht

Signed-off-by: Max Lambrecht <max.lambrecht@hpe.com>

**Pull Request check list**

- [ ] Proper tests/regressions included?
- [ ] Documentation updated?

**Affected functionality**

**Description of change**

Refactor to organize the responsibilities of the entities across the codebase: 

- Created a Server and Harvester entities that start Endpoints with TCP and UDS addresses. 
- Created and moved around new Config structs for handling the configurations where they need to be (e.g., CLI configs reading from config files are now in the CMD folder)
- Refactored Catalog to have one for the Harvester and other for the Server (although theses objects will not be needed for the PoC implementation)
- Converted to structs some interfaces that are not good abstractions (e.g., the HarvesterController).
- Added a MemStore to be used as long as we don't have an actual datastore implementation, and probably enough for a PoC. 
- Added the `generate token` functionality, although there is some room for improvement.
- Added `logrus` for Logging instead of using a handmade Logger.
- Some other minor changes like adding or changing config options in the conf files. 

** This refactor may be breaking some functionality, although Server and Harvester are running **

**Which issue this PR fixes**

2022-09-12 12:59 UTC, mgbcaio requested changes
This is fantastic, Max L. thanks for the refactoring. I left some nit comments and other than that we have some GitHub actions lint failures if you could check those =)

2022-09-12 12:59 UTC, mgbcaio commented on pkg/common/telemetry/names.go
> +	Su
why is this here ?

2022-09-12 12:59 UTC, mgbcaio commented on pkg/common/telemetry/names.go
> +	// SubsystemName declares field for some subsystem name (an API, module...)
```suggestion
	// SubsystemName declares a field for some subsystem name (an API, module...)
```

2022-09-12 12:59 UTC, mgbcaio commented on cmd/harvester/cli/cli.go
> +		log: logrus.WithField(telemetry.SubsystemName, telemetry.Harvester),
oh nice!!! 💯

2022-09-12 12:59 UTC, mgbcaio commented on cmd/harvester/cli/config.go
> +func ParseConfig(config io.Reader) (*Config, error) {
this function is the same present in the server, do you think we could extract it to only have it implemented once? (maybe put it inside a util package or something like that).

2022-09-12 12:59 UTC, mgbcaio commented on pkg/harvester/client/server.go
> +// GaladrielServerClient represents a client to connecto to Galadriel Server
```suggestion
// GaladrielServerClient represents a client to connect to Galadriel Server
```

2022-09-12 12:59 UTC, mgbcaio commented on pkg/common/util/task.go
> +// RunTasks runs all the given tasks concurrently and waits for all of them to completed.
```suggestion
// RunTasks runs all the given tasks concurrently and waits for all of them to be completed.
```

2022-09-12 20:58 UTC, mchurichi commented on cmd/server/cli/config.go
> +	ip := net.ParseIP(c.Server.ListenAddress)
This should allow either a hostname or IP address to provide flexible interface binding

2022-09-12 20:58 UTC, mchurichi commented on cmd/server/cli/config.go
> +		return nil, errors.Wrap(errors.New("configuration file is empty"), "bad configuration")
AFAIK the idea behind wrapping an error is to allow callers to assert if a wrapped error is a specific error implementation, but since we are not exposing "bad configuration" here, not sure if this makes sense

2022-09-12 20:58 UTC, mchurichi commented on cmd/server/cli/run.go
> +			}
does it make sense to have file reading and config mapping here? it feels we'll be reusing this

2022-09-12 20:58 UTC, mchurichi commented on pkg/server/endpoints/endpoints.go
> +			return
don't we need to return some kind of error if this fails?

2022-09-12 20:58 UTC, mchurichi commented on pkg/server/datastore/datastore.go
> +	CreateJoinToken(context.Context, *JoinToken) error
It's usually a good idea to have all create and update methods returning the newly created/updated object

2022-09-12 20:58 UTC, mchurichi commented on pkg/harvester/endpoints/endpoints.go
> +		tcpServer.Close()
shouldn't we have these defer'ed after starting the servers? as a panic before reaching this point will prevent an appropriate cleanup

2022-09-13 12:47 UTC, mchurichi commented on pkg/harvester/endpoints/endpoints.go
> +	case err = <-errLocalServer:
remove, use, or
```suggestion
	case err = <-errLocalServer: //nolint:ineffassign
```

2022-09-13 15:40 UTC, maxlambrecht commented on pkg/common/telemetry/names.go
> +	Su
Oops

2022-09-13 17:04 UTC, maxlambrecht commented on cmd/harvester/cli/config.go
> +func ParseConfig(config io.Reader) (*Config, error) {
The functions are not the same, the return types are different, one is `harvester.Config` and the other is `server.Config`

2022-09-13 17:29 UTC, jufantozzi commented on pkg/harvester/catalog/catalog.go
> +type Catalog interface {
Can we please have a description for this interface? personally this was one of the things I found hard to understand the meaning of in SPIRE (still not comfortable as I'd like 😅 )

2022-09-13 18:03 UTC, jufantozzi reviewed
Regarding POC scope, LGTM!

2022-09-13 19:30 UTC, jufantozzi commented
BTW regarding the datastore implementation, I can incorporate the token logic into the other PR to avoid conflicts

2022-09-13 22:41 UTC, maxlambrecht commented on cmd/server/cli/config.go
> +	ip := net.ParseIP(c.Server.ListenAddress)
That would be complicated, as the TCPAddr object uses an IP, if we accept a hostname we would need to look up the name to obtain the IP.

2022-09-13 22:43 UTC, maxlambrecht commented
I addressed some of the comments, still working through all the comments. And also I'm removing some components that won't be necessary.

2022-09-13 22:58 UTC, mchurichi commented on cmd/server/cli/config.go
> +	ip := net.ParseIP(c.Server.ListenAddress)
ok it makes sense, no reason to add this complexity for a PoC

2022-09-15 15:53 UTC, jufantozzi commented
more thoughts on the database: we can follow with the `in-mem` until we're done with the poc. Then we eventually start implementing the interface for the `sqlstore`, WDYT?

2022-09-15 15:56 UTC, maxlambrecht commented
> more thoughts on the database: we can follow with the `in-mem` until we're done with the poc. Then we eventually start implementing the interface for the `sqlstore`, WDYT?

yes, we can make the DB CRUD methods use some structure in memory to store the objects.

2022-09-19 17:20 UTC, jufantozzi commented on pkg/harvester/client/server.go
> +func (s *client) GetMemberships(ctx context.Context) ([]string, error) {
are we keeping memberships for POC?

2022-09-19 17:31 UTC, maxlambrecht commented on cmd/server/cli/config.go
> +		return nil, errors.Wrap(errors.New("configuration file is empty"), "bad configuration")
You are right, it doesn't make sense. 
It was not on purpose, I moved that method from another file and it already had that return statement.

2022-09-19 18:52 UTC, maxlambrecht commented on pkg/harvester/client/server.go
> +func (s *client) GetMemberships(ctx context.Context) ([]string, error) {
removed

2022-09-20 10:59 UTC, jufantozzi submitted a review, later dismissed

2022-09-20 13:24 UTC, mgbcaio submitted a review, later dismissed

2022-09-20 13:30 UTC, mchurichi commented on pkg/harvester/spire/spire.go
> +		return nil, fmt.Errorf("failed to dial API socket: %w", err)
not a huge concern, but wouldn't we leaking implementation details (internal components error) if we wrap these errors?

2022-09-20 13:31 UTC, mchurichi commented on pkg/harvester/spire/spire.go
> +		return nil, fmt.Errorf("failed to dial API socket: %w", err)
I think we should only wrap errors if it's an error we implement and expose

2022-09-20 13:34 UTC, mchurichi commented on cmd/server/util/client.go
> +	r, err := c.client.Get("http://unix/token")
where does this URL come from?

2022-09-20 14:44 UTC, maxlambrecht commented on cmd/server/util/client.go
> +	r, err := c.client.Get("http://unix/token")
the Get method requires a well-formed URL with the Scheme and Host components, although that's irrelevant for a call on a Unix domain socket. Only the path "/token" is important

2022-09-20 21:01 UTC, mchurichi approved these changes

2022-09-20 21:10 UTC, mgbcaio approved these changes

2022-09-20 22:12 UTC, merged