Create member and relationship - API through database
HewlettPackard/galadriel pull request #50
Opened 2022-09-21 19:00 UTC by jufantozzi

**Pull Request check list**

- [ ] Proper tests/regressions included?
- [ ] Documentation updated?

**Affected functionality**

-  Implements two new commands `create member` and `create relationship`. These are still to be updated once we implement the manager for the server.
- Updates `create token` command so now it accepts a `memberID` to properly associate a token to a member
- Remove support for FetchJoinToken and DeleteJoinToken
- Renames `GenerateJoinToken` > `GenerateAccessToken` and renames `Endpoints` > `EndpointHandler`
**Description of change**

Tests that broke were not fix and new tests were not written, as we agreed for the POC. Please let me know if this is a miss-understanding.

2022-09-21 21:08 UTC, maxlambrecht reviewed
Good job! I've done a first pass and left a few comments.

2022-09-21 21:08 UTC, maxlambrecht commented on pkg/common/entities.go
> +	Expiry time.Time
Add a MemberID here and move the tokens list to its own entity, that way it will be easier to find a token when it needs to be validated (e.g., Harvester sends a token the first time to do the onboarding)

2022-09-22 10:20 UTC, jufantozzi commented on cmd/server/cli/create.go
> +		fmt.Println("Token:", m.Tokens[0])
are we not creating a token when creating a user? or are we not returning it?

2022-09-22 10:39 UTC, jufantozzi commented on cmd/server/cli/generate.go
> +	Short: "Generates an access token for provided memberID",
thought about this specifically but went with memberID for simplicity
but sure, i'll change it, agree it's where we want to end up at

2022-09-22 11:31 UTC, mchurichi commented on pkg/common/entities.go
> +	Expiry time.Time
what you mean by move to its own entity? having AccessToken + a Token entity? what's the rationale behind this?

2022-09-22 11:34 UTC, mchurichi commented on pkg/common/entities.go
> +	Expiry time.Time
oh nvm, I see what you mean, is it related to the Tokens list in the Member struct?

2022-09-22 11:35 UTC, mgbcaio requested changes

2022-09-22 11:35 UTC, mgbcaio commented on cmd/server/cli/create.go
> +		}
nit: empty line separating the if's

2022-09-22 11:35 UTC, mgbcaio commented on cmd/server/cli/create.go
> +		idB, err := uuid.Parse(args[0])
I think this should be `args[1]`

2022-09-22 11:35 UTC, mgbcaio commented on cmd/server/util/client.go
>  	defer r.Body.Close()
nit: empty line

2022-09-22 11:35 UTC, mgbcaio commented on cmd/server/util/client.go
> +	defer r.Body.Close()
nit: empty line

2022-09-22 11:35 UTC, mgbcaio commented on cmd/server/util/client.go
> +	r, err := c.client.Post(createTokenURL, "application/json", bytes.NewBuffer(b))
nit: add empty line

2022-09-22 11:35 UTC, mgbcaio commented on cmd/server/util/client.go
> +	}
nit: add empty line

2022-09-22 11:35 UTC, mgbcaio commented on pkg/server/endpoints/management.go
> +		}
nit: add empty line

2022-09-22 11:35 UTC, mgbcaio commented on pkg/server/endpoints/management.go
> +		}
nit: add empty line

2022-09-22 11:35 UTC, mgbcaio commented on pkg/server/endpoints/management.go
> +		}
nit: add empty line

2022-09-22 11:35 UTC, mgbcaio commented on pkg/server/endpoints/management.go
> +		}
nit: add empty line

2022-09-22 11:35 UTC, mgbcaio commented on pkg/server/endpoints/management.go
> +		}
nit: add empty line

2022-09-22 11:35 UTC, mgbcaio commented on pkg/server/endpoints/management.go
> +		}
nit: add empty line

2022-09-22 11:40 UTC, mchurichi commented on cmd/server/cli/create.go
> +	Short: "Register a new member and return its associated access token.",
```suggestion
	Short: "Registers a new member and returns its associated access token.",
```

2022-09-22 11:41 UTC, mchurichi commented on cmd/server/cli/create.go
> +	Short: "Register a new relationship.",
```suggestion
	Short: "Registers a new relationship.",
```

2022-09-22 12:02 UTC, mchurichi commented on pkg/server/endpoints/run.go
> +	e.createMemberHandler(ctx)
nit: I'd suggest to separate handlers from endpoint definitions, something like this

```suggestion
	http.HandleFunc("/createMember", handleCreateMember)
	http.HandleFunc("/createRelationship", handleCreateRelationship)
	// etc
```

2022-09-22 13:13 UTC, maxlambrecht commented on cmd/server/cli/create.go
> +		fmt.Println("Token:", m.Tokens[0])
We are no creating tokens when creating members, and we shouldn't print tokens when creating members.

2022-09-22 13:21 UTC, maxlambrecht commented on pkg/server/datastore/datastore.go
> +
exactly, we should keep the tokens list here

2022-09-22 13:22 UTC, maxlambrecht commented on pkg/server/datastore/datastore_test.go
> +//func TestJoinTokenMethods(t *testing.T) {
don't comment code, just delete it.

2022-09-22 13:25 UTC, maxlambrecht commented on cmd/server/cli/create.go
> +	Use:   "relationship <memA> <memB>",
Agreed, I like it more with trust domains, also thinking about a demo, it would be nicer and more clear if we can just pass the trust domains to the commands.

2022-09-22 13:29 UTC, maxlambrecht commented on cmd/server/cli/generate.go
> +	Short: "Generates an access token for provided memberID",
Agreed, eventually we'll need more properties than just the trust domain, but for now the trust domain is enough to identify a member, and it's more user friendly thinking in presenting a demo.

2022-09-22 14:17 UTC, jufantozzi commented on pkg/common/entities.go
> +	Expiry time.Time
yes, since the first call will not have a memberID to it, would make it harder to look it up

2022-09-26 12:50 UTC, mgbcaio commented on cmd/server/util/client.go
> +	createdMember := &datastore.Member{}
As I need to use the variable to make the unmarshaling of the JSON, shouldn’t it be initialized like this ? If I change your method I keep getting nil error, any thoughts?

2022-09-26 16:28 UTC, mgbcaio commented on cmd/server/cli/create.go
> +	createMemberCmd.Flags().StringVar(&memberName, "name", "", "member name")
I will be removing this since we are not going to use member names for the POC and instead will use the trust domain. Since the name is an optional flag, no need for that now.

2022-09-26 19:22 UTC, maxlambrecht commented on cmd/server/util/client.go
> +	r, err := c.client.Post(createRelationshipURL, contentType, bytes.NewBuffer(relBytes))
```suggestion
	r, err := c.client.Post(createRelationshipURL, contentType, bytes.NewReader(relBytes))
```

2022-09-26 19:22 UTC, maxlambrecht commented on cmd/server/util/client.go
> +	bytes.NewBuffer(relBytes)
Remove this line.

2022-09-26 19:22 UTC, maxlambrecht commented on cmd/server/util/client.go
> +	GenerateAccessToken(trustDomain string) (*datastore.AccessToken, error)
Why don't use  `common.AccessToken`?

2022-09-26 19:22 UTC, maxlambrecht commented on cmd/server/util/client.go
> +	CreateMember(m common.Member) error
Pass pointers to structs.

2022-09-26 19:35 UTC, jufantozzi commented on cmd/server/util/client.go
> +	GenerateAccessToken(trustDomain string) (*datastore.AccessToken, error)
agreed

2022-09-26 20:11 UTC, maxlambrecht commented on cmd/server/util/client.go
> +	_, err = c.client.Post(createMemberURL, contentType, bytes.NewBuffer(memberBytes))
The `Post` method needs something that implements the `io.Reader` interface, in that regard both `Reader` and `Buffer` structs implement it, but `Buffer` implements more methods that we don't need and it's more complex.

2022-09-28 14:17 UTC, maxlambrecht approved these changes
🍰

2022-09-28 14:45 UTC, mgbcaio approved these changes

2022-09-28 14:46 UTC, merged