harvester endpoints
HewlettPackard/galadriel pull request #52
Opened 2022-09-29 17:46 UTC by jufantozzi

**Description of change**

Early PR to gather feedback on the discussed logic for the endpoints. 

Complete changelog:
* General cleanups and refactors:
    * CLI package (cleanup),
    * Common package and
    * Endpoints package (split in admin and harvester package).
* Implements 2 new endpoints, `/bundle/sync` and  `/bundle`. The code for these endpoints _should be_ functional but still very “raw”. It should be better encapsulated.
* Creates a very basic testing make target for the implemented endpoints. This should be improved and be leveraged by our pipeline at some point.

2022-10-04 12:07 UTC, jufantozzi commented on Makefile
> +	token=`./bin/galadriel-server generate token -t td2 | ggrep -Po "(?<=Access Token:\s).*"`; \
```suggestion
	token=`./bin/galadriel-server generate token -t td2 | grep -Po "(?<=Access Token:\s).*"`; \
```

2022-10-04 12:22 UTC, mgbcaio commented
Excellent job, Juliano. I think this PR will have a lot of conflicts with the others, or the other PRs will have conflicts with this xD
I suggest we look into this to decide which implementation we are going to choose (since you removed the `draft` label)

2022-10-04 12:32 UTC, jufantozzi commented
> I suggest we look into this to decide which implementation we are going to choose
What implementation do you mean? the code for this PR should be complete by now

2022-10-04 12:36 UTC, mgbcaio commented
> > I suggest we look into this to decide which implementation we are going to choose
> 
> What implementation do you mean? the code for this PR should be complete by now

There are things you changed that were also changed in other PRs, that's pretty much it. for example the `addHandlers` method, just to avoid conflicts, either you or Maxi would need to change the file =)

Same for the paths in the `cmd/server/util/client.go` file and so on, map those conflicts would take a lot of time xD

2022-10-04 12:38 UTC, mgbcaio commented
> > I think this PR will have a lot of conflicts with the others, or the other PRs will have conflicts with this
> 
> My impression is that those conflicts will be minor and hopefully easy to handle. The changes introduced by #57 should take a more careful merge than #56 or #54, but nothing really complicated as same functions were not touched.

Fixing it now or later does not matter, as long as we do not have more work than we intend to. Just saying to keep an eye on this, since conflicts will occur.

2022-10-04 12:43 UTC, jufantozzi commented
> Fixing it now or later does not matter, as long as we do not have more work than we intend to. Just saying to keep an eye on this, since conflicts will occur.

Sometimes you can't avoid conflicts and thats okay too =) I did a small refactor because we had 2 http servers and handlers on a single package and it was getting clunky. Code was simply split into different packages, that shouldn't really be a big problem for maxi to work around. If I'm seeing this wrong, @mchurichi please feel free to drop in whenever.

2022-10-04 12:48 UTC, mchurichi commented
> 

Agree @jufantozzi, I didn't really add much, just a couple of new methods that can be easily carried over to the right file.

2022-10-04 12:50 UTC, mgbcaio commented
> > Fixing it now or later does not matter, as long as we do not have more work than we intend to. Just saying to keep an eye on this, since conflicts will occur.
> 
> Sometimes you can't avoid conflicts and thats okay too =) I did a small refactor because we had 2 http servers and handlers on a single package and it was getting clunky. Code was simply split into different packages, that shouldn't really be a big problem for maxi to work around. If I'm seeing this wrong, @mchurichi please feel free to drop in whenever.

yeah, of course, just bringing this up so that we can solve it together =P

2022-10-04 13:32 UTC, jufantozzi commented
Just solidifying the decided order of merges discussed offline with @mchurichi:

1. First we merge #54 and #57, which are easily rebasable into this one
2. Then we rebase and merge this PR
3. Then #56 can we be rebased with all the changes

2022-10-04 17:45 UTC, maxlambrecht reviewed
I have a big concern with the refactor of the server/endpoints: How would you do if you wanted later on to add a new api to one of the servers? Or if you wanted to expose one of the existing apis on a different transport (e.g. admin api on TCP)? You would need to refactor everything again, right?

2022-10-04 17:45 UTC, maxlambrecht commented on pkg/server/api/harvester/handlers.go
> +	for _, r := range current {
This method needs to be refactored into smaller functions, there's too much nesting of control loops and if statements.

2022-10-04 17:48 UTC, jufantozzi commented on pkg/server/api/harvester/handlers.go
> +		TrustDomain: spiffeid.RequireTrustDomainFromString("spiffe://td2"),
Ops! this is a left over used for testing pourposes but I somehow missed it! thanks!
 I will update with the proper way to get the token

2022-10-04 17:49 UTC, jufantozzi commented on Makefile
> +create-relationship:
my plan was to remove these soon in the future and have actual integration testing, WDYT?

2022-10-04 17:55 UTC, maxlambrecht commented on Makefile
> +create-relationship:
I prefer to have separate from the main Makefile, but I leave it to you.

2022-10-04 18:15 UTC, mgbcaio commented on pkg/server/api/admin/handlers.go
> +		s.handleError(w, err)
the `handleError` function already logs the error, do we need bot logs ? (handleError and the line 58) ?

2022-10-04 18:15 UTC, mgbcaio commented on pkg/server/api/harvester/handlers.go
> +	logger := ctx.Logger()
Why aren't we using the directly the logger from the echoServer ? `s.config.Logger` Also applies to the other functions

2022-10-04 18:28 UTC, jufantozzi commented
>I have a big concern with the refactor of the server/endpoints: How would you do if you wanted later on to add a new api to one of the servers? Or if you wanted to expose one of the existing apis on a different transport (e.g. admin api on TCP)? You would need to refactor everything again, right?

Great point, yes, we would need more refactor to be able to have a way to properly "plug" different transports and be able to re-use the handlers. 

Im wondering if we split the handlers into their own packages, and have the run function receiving the transport type via config, it could work, right? If positive, I can try to implement it this way

2022-10-04 18:30 UTC, jufantozzi commented on pkg/server/api/harvester/handlers.go
> +	logger := ctx.Logger()
no real reason, we should be fixing that in #56

2022-10-04 18:35 UTC, jufantozzi commented
>>I have a big concern with the refactor of the server/endpoints: How would you do if you wanted later on to add a new api to one of the servers? Or if you wanted to expose one of the existing apis on a different transport (e.g. admin api on TCP)? You would need to refactor everything again, right?

>Great point @maxlambrecht, yes, we would need more refactor to be able to have a way to properly "plug" different transports and be able to re-use the handlers.
Im wondering if we split the handlers into their own packages, and have the run function receiving the transport type via config, it could work, right? If positive, I can try to implement it this way

Giving it a second thought, this goes back to some discussions we had a good time ago, where essentially these handlers would require library specific contracts (like echo.Context) and that would make it really difficult to be able to properly re-use it.

2022-10-04 23:14 UTC, mchurichi commented on pkg/server/api/harvester/handlers.go
> +		logger.Infof("Trust domain %s has been successfully updated", receivedHarvesterState.TrustDomain)
Same here. As a rule of thumb: use `Info` for high level component's lifecycle events and their relevant messages, and `Debug` for internal details that could be useful for someone looking deeper (bug hunting, performance issues, etc)
```suggestion
		logger.Debugf("Trust domain %s has been successfully updated", receivedHarvesterState.TrustDomain)
```

2022-10-04 23:14 UTC, mchurichi commented on pkg/server/datastore/datastore.go
> +	GetMember(ctx context.Context, trustDomain string) (*Member, error)
What's the difference between `Get` and `Fetch`? if there is none, we should stick to one verb. I'd rather use Get but it's just a personal preference.

2022-10-04 23:14 UTC, mchurichi commented on pkg/server/datastore/datastore.go
> +		return nil, errors.New("failed updating member: member not found")
```suggestion
		return nil, errors.New("failed getting member: member not found")
```

2022-10-04 23:14 UTC, mchurichi commented on pkg/server/datastore/datastore.go
> +	defer s.mu.Unlock()
```suggestion
	s.mu.RLock()
	defer s.mu.RUnlock()
```

2022-10-04 23:14 UTC, mchurichi commented on pkg/server/datastore/datastore.go
> +	defer s.mu.Unlock()
```suggestion
	s.mu.RLock()
	defer s.mu.RUnlock()
```

2022-10-04 23:14 UTC, mchurichi commented on pkg/server/datastore/datastore.go
> +func (s *MemStore) GetRelationship(_ context.Context, trustDomain string) ([]*Relationship, error) {
```suggestion
func (s *MemStore) GetRelationships(_ context.Context, trustDomain string) ([]*Relationship, error) {
```

2022-10-04 23:14 UTC, mchurichi commented on pkg/server/datastore/datastore.go
> +				return nil, errors.New("failed updating member: member not found")
```suggestion
				return nil, errors.New("failed getting relationship: member not found")
```

2022-10-04 23:14 UTC, mchurichi commented on pkg/server/datastore/datastore.go
> +				return nil, errors.New("failed updating member: member not found")
```suggestion
				return nil, errors.New("failed getting member: member not found")
```

2022-10-05 10:55 UTC, mchurichi requested changes
Thanks for putting this together! ❤️ I believe overall looks very good.
Just left some suggestions and questions here and there, mostly nitpicks about error logging, mutexes usage, and naming schemes. There are only a few breaking deals about bundle hash verification and authentication we need to take care of.

2022-10-05 17:14 UTC, maxlambrecht commented on pkg/common/api.go
> +	TrustBundleHash []byte `json:"trust_bundle_hash"`
Discussed this offline with @mchurichi , crypto APIs accept and return `[]byte` type for hashes, so it makes sense to keep as that.

2022-10-05 18:32 UTC, jufantozzi commented
taking this one down in favor of splitting up the endpoints and the refactoring

2022-10-05 18:32 UTC, closed without merging