Thisab
HewlettPackard/Galadriel pull request #9
Opened 2022-07-21 19:11 UTC by thisab

**Pull Request check list**

- [ ] Proper tests/regressions included?
- [ ] Documentation updated?

**Affected functionality**

**Description of change**

**Which issue this PR fixes**

2022-07-21 19:59 UTC, mchurichi requested changes
Thanks for this, Thiago!. I just left a suggestion to point to the right Harvester API spec and we'll be good to go 💯

2022-07-21 19:59 UTC, mchurichi commented on dev/api/harvester.html
> +        <elements-api apiDescriptionUrl="api_server.yaml" router="hash" />
```suggestion
        <elements-api apiDescriptionUrl="api_harvester.yaml" router="hash" />
```

2022-07-21 21:11 UTC, jufantozzi approved these changes
LGTM 👍

2022-07-21 21:14 UTC, mchurichi reviewed
💯

2022-07-21 21:14 UTC, mchurichi approved these changes

2022-07-21 21:16 UTC, mchurichi commented
We just need the commits to be signed and we can get this merged 💯

2022-07-25 14:58 UTC, n-th approved these changes

2022-07-26 16:34 UTC, mchurichi commented
could you please merge the latest changes from master? I think that would fix the trivy issue, but the yamls have been moved and we'll need to update the paths here

2022-07-26 16:49 UTC, thisab commented
i think it would be easier if we dropped this request. So I would pull again and work on the new structure

2022-07-26 16:49 UTC, closed without merging